name: Spring Boot CICD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker image
        run: docker build -t app:1 .

      
      - name: Create .env file
        run: |
          echo "POSTGRES_USER=${{ secrets.USER }}" > .env
          echo "POSTGRES_PASSWORD=${{ secrets.PASSWD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.DATABASE }}" >> .env
          echo "SPRING_DATASOURCE_URL=${{ secrets.APP_CREDS_URL }}" >> .env
          echo "SPRING_DATASOURCE_USERNAME=${{ secrets.APP_CREDS_USERNAME }}" >> .env
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.APP_CREDS_PASSWD }}" >> .env

      
      - name: Stop old containers
        run: docker compose down || true

    
      - name: Run containers
        run: docker compose up -d --build


      
