name: Spring Boot 

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set environment variables
        run: |
         echo "POSTGRES_USER=${{ secrets.USER }}" >> $GITHUB_ENV
         echo "POSTGRES_PASSWORD=${{ secrets.PASSWD }}" >> $GITHUB_ENV
         echo "POSTGRES_DB=${{ secrets.DATABASE }}" >> $GITHUB_ENV

         echo "SPRING_DATASOURCE_URL=${{ secrets.APP_CREDS_URL }}" >> $GITHUB_ENV
         echo "SPRING_DATASOURCE_USERNAME=${{ secrets.APP_CREDS_USERNAME }}" >> $GITHUB_ENV
         echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.APP_CREDS_PASSWD }}" >> $GITHUB_ENV

       run: mvn clean install

      - name: Build Docker image
        run: docker build -t app:1 .

      - name: Stop old container
        run: docker stop app || true

      - name: Remove old container
        run: docker rm app || true

      - name: Run container
        run: docker compose up -d --build
